# Get the host path
# I am using Windows and so this is the host path
# For MAC the path is "/private/etc/hosts"
hostpath = "C:\\Windows\\System32\\drivers\\etc\\hosts"

# loacalhost (will redirect to this host)
redirect = "127.0.0.1"

websitelist = [
    "www.pornhub.com",
    "www.xvideos.com",
    "www.xhamster.com",
    "www.xnxx.com",
    "www.youporn.com",
    "www.redtube.com",
    "www.porn.com",
    "www.tube8.com",
    "www.ixxx.com",
    "www.sunporno.com",
    "www.pornhat.com",
    "www.porn300.com",
    "www.pornone.com",
    "www.sexvid.xxx",
    "www.thumbzilla.com",
    "zbporn.com",
    "www.fuq.com",
    "ok.xxx",
    "beeg.com",
    "www.tubegalore.com",
    "xxxbunker.com",
    "www.3movs.com",
    "www.cumlouder.com",
    "porndoe.com",
    "xbabe.com",
    "vipwank.com",
    "www.porndroids.com",
    "www.alohatube.com",
    "www.maturetube.com",
    "www.tubev.sex",
    "www.4tube.com",
    "www.shameless.com",
    "www.megatube.xxx",
    "www.porntube.com",
    "www.porndig.com",
    "www.pornburst.xxx",
    "www.bigporn.com",
    "www.porn.biz",
    "fapvidhd.com",
    "www.melonstube.com",
    "tastyblacks.com",
    "www.lobstertube.com",
    "fapster.xxx",
    "viviporn.tv",
    "pornfaze.com",
    "pornmaki.com",
    "www.pornid.xxx",
    "www.hotporntubes.com",
    "pornito.xxx",
    "thematureporn.net",
    "www.xxxvideos247.com",
    "handjobhub.com",
    "www.dansmovies.com",
    "www.porn7.xxx",
    "www.forhertube.com",
    "www.pornheed.com",
    "www.orgasm.com",
    "www.pornrabbit.com",
    "www.tiava.com",
    "www.fux.com",
    "www.metaporn.com",
    "www.pornerbros.com",
    "pornplanner.com",
    "hentaihaven.xxx",
    "mypornbible.com",
    "www.badjojo.com",
    "findtubes.com",
    "www.pornmd.com",
    "www.nudevista.com",
    "hentaigasm.com",
    "www.fakku.net",
    "gelbooru.com",
    "porcore.com",
    "www.cartoonporno.xxx",
    "www.nutaku.net",
    "porngameshub.com",
    "69games.xxx",
    "gamcore.com",
    "www.gamesofdesire.com",
    "sexemulator.com",
    "hooligapps.com",
    "assist.lifeselector.com",
    "www.siliconwives.com",
    "www.yourdoll.com",
    "www.sexysexdoll.com",
    "sexyrealsexdolls.com",
    "www.joylovedolls.com",
    "forum.adultdvdtalk.com",
    "www.shemalehd.sex",
    "www.anyshemale.com",
    "www.ashemaletube.com",
    "www.tranny.one",
    "besttrannypornsites.com",
    "avn.com",
    "perezhilton.com",
    "www.maxim.com",
    "flingster.com",
    "onlinefreechat.com",
    "www.nakednews.com",
    "www.lesbian8.com",
    "www.girlsway.com",
    "landing.rk.com",
    "www.g2fame.com",
    "www.digitalplayground.com",
    "landing.mofosnetwork.com",
    "landing.twistysnetwork.com",
    "faphouse.com",
    "landing.bangbrosnetwork.com",
    "enter.private.com",
    "join.newsensations.com",
    "nubiles.net",
    "join.teamskeet.com",
    "www.g2fame.com",
    "bestpaypornsites.com",
    "onlyfans.com",
    "awejmp.com",
    "imlive.com",
    "awejmp.com",
    "www.slutroulette.com",
    "vrporn.com",
    "vrbangers.com",
    "www.vrsmash.com",
    "badoinkvr.com",
    "www.wankzvr.com",
    "www.czechvr.com",
    "www.sexlikereal.com",
    "go.stripchat.com",
    "tour.camsoda.com",
    "jerkmate.com",
    "liveporngirls.com",
    "iptorrents.com",
    "pussytorrents.org",
    "www.gaymaletube.com",
    "manporn.xxx",
    "www.youporngay.com",
    "www.gayfuror.com",
    "www.justusboys.com",
    "filf.com",
    "myporngay.com",
    "www.assoass.com",
    "bigassporn.tv",
    "viewgals.com",
    "www.hotpornphotos.com",
    "www.pichunter.com",
    "www.nakedpornpics.com",
    "stufferdb.com",
    "www.pornpics.com",
    "www.youx.xxx",
    "www.zenra.net",
    "vjav.com",
    "bdsmstreak.com",
    "www.punishbang.com",
    "www.clips4sale.com",
    "www.bellesa.co",
    "www.stasyq.com",
    "thechive.com"
]

with open(hostpath, "r+") as file:
        content = file.read()
        for website in websitelist:
            # if your website is not in the `host` file, add the website
            if not website in content:
                with open(hostpath, "a") as writefile:
                    writefile.write(redirect + " " + website + "\n")
                    writefile.write(redirect + " https://" + website + "\n")
